public class PropertyAndUnitRequestWrapper {
    public String assetType;	
    public String propertyType;	
    public String unitType;	
    public String propertyStatus;	
    public Decimal numberofBedrooms;	
    public Decimal numberofBathrooms;
    public Integer numberofParkingArea;
    public string additionalStorageSpace;
    public Integer squareFootage;
    public Integer noOfSeatingSpace;
    public string displayfeatures;
    public String furnishing;
    public String rentOrBuy;
    public String currencyCode;
    public Integer budget;
    public string[] amenities;
    public String locationPreference;
    public String state;
    public String city;
}